# Generated by Django 4.1.5 on 2023-01-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=50)),
                ('emotion', models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1)])),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_data', to='sentiment.history')),
            ],
        ),
    ]
