# Generated by Django 4.1.5 on 2023-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='aspect',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
