# Generated by Django 4.1.5 on 2023-01-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_alter_data_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_input',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
